-- 코드를 입력하세요
# SELECT DATE_FORMAT(DATETIME, '%h') AS HOUR, COUNT(*) AS COUNT
# FROM ANIMAL_OUTS
# WHERE HOUR BETWEEN 9 AND 19
# GROUP BY HOUR
# ORDER BY HOUR;
SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR;